ahoyapi: v2

commands:
    learner:
        usage: start learner
        cmd: python experiment.py 
                --job_name=learner 
                --task=0 
                --num_actors=1 
                --batch_size=32 
                --entropy_cost=0.003333913 
                --learning_rate=0.000318669956 
                --total_environment_frames=100000000000 
                --reward_clipping=soft_asymmetric

    actor:
        usage: start actor
        cmd: python experiment.py \
                --job_name=actor \
                --task=0 \
                --num_actors=1 \
                --level_name=dmlab30
